dbt_pipelines:
  outputs:
    dev:
      dbname: db_brt_bus
      host: db-datalake-service
      pass: postgres
      port: 5432
      schema: sc_silver
      threads: 1
      type: postgres
      user: postgres
  target: dev