FROM postgres:latest

# Define as variáveis de ambiente
ENV POSTGRES_DB db_brt_bus
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres

# Copia o script para a pasta de inicialização do PostgreSQL
COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432